name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true

    - name: Go version
      run: go version

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Benchmark
      run: go test -bench=. -run=XXX -benchmem -v ./...

    - name: FuzzSaltWithLabel
      run: go test -fuzz=FuzzSaltWithLabel -run=XXX -fuzztime=1m -v .

    - name: FuzzX25519IdentityFromKey
      run: go test -fuzz=FuzzX25519IdentityFromKey -run=XXX -fuzztime=1m -v .

    - name: FuzzX25519IdentityFromPasswordWithParameters
      run: go test -fuzz=FuzzX25519IdentityFromPasswordWithParameters -run=XXX -fuzztime=1m -v .
